apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kafkatopics.hybridcloud.maibornwolff.de
spec:
  scope: Namespaced
  group: hybridcloud.maibornwolff.de
  names:
    kind: KafkaTopic
    plural: kafkatopics
    singular: kafkatopic
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                brokerRef:
                  type: object
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                  required:
                    - name
                # allowedK8sNamespaces:
                #   type: array
                #   items:
                #     type: string
                kafka:
                  type: object
                  properties:
                    partitions:
                      type: integer
                    retentionInDays:
                      type: integer
                credentialsSecret:
                  type: string
              required:
                - credentialsSecret
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              nullable: true
