apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kafkabrokers.hybridcloud.maibornwolff.de
spec:
  scope: Namespaced
  group: hybridcloud.maibornwolff.de
  names:
    kind: KafkaBroker
    plural: kafkabrokers
    singular: kafkabroker
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                backend:
                  type: string
                size:
                  type: object
                  properties:
                    class:
                      type: string
                credentialsSecret:
                  type: string
                # allowedK8sNamespaces:
                #   type: array
                #   items:
                #     type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              nullable: true
