apiVersion: v2
name: hybrid-cloud-kafka-operator
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: "0.1.0"

dependencies:
  - name: strimzi-kafka-operator
    version: "~0.31.1"
    repository: https://strimzi.io/charts/
    condition: strimzi.enabled
