replicaCount: 1

image:
  repository: ghcr.io/maibornwolff/hybrid-cloud-kafka-operator
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "dev"

imagePullSecrets: []
nameOverride: "hybrid-cloud-kafka-operator"
fullnameOverride: "hybrid-cloud-kafka-operator"

serviceAccount:
  # Specifies whether a service account with permissions should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  name: null
  # This is required if the operator should install strimzi instances, can be disabled if you only use the Azure Event Hub backend
  clusterAdmin: true

# Operator config.yaml
operatorConfig: |
  backend: strimzi
  backends:
    strimzi: {}

# The name of a secret whose data will be provided to the operator as environment variables (using the envFrom mechanism)
# Use this to provide sensitive information like azure credentials to the operator
envSecret: null

# A list of environment variables (with name, value) to provide to the operator
extraEnv: []

# List of volumes to mount into the operator pod
volumes: []
# List of volume mounts for the operator pod
volumeMounts: []


# Extra annotations to add to the operator pods
podAnnotations: {}

# Extra labels to add to the operator pods
podLabels: {}

podSecurityContext: {}

securityContext: {}

pod:
  ports:
    - name: http
      containerPort: 8080
      protocol: TCP

  livenessProbe:
    httpGet:
      path: /healthz
      port: http
  readinessProbe:
    httpGet:
      path: /healthz
      port: http
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

service:
  type: ClusterIP
  port: 80
  targetPort: http

nodeSelector: {}

tolerations: []

affinity: {}

strategy:
  type: Recreate


strimzi:
  # Also deploy the strimzi kafka operator
  enabled: true

# To configure strimzi add any values here
#strimzi-kafka-operator:
